### ISSUE TITLE
can't install this package

### ISSUE THREAD

**Issue by kodermax** [Algo-Web/POData-Laravel#134]
I have this error
![image](https://user-images.githubusercontent.com/590985/32238947-3e8055e2-be7a-11e7-85a5-38f45a393829.png)

**Comment by CyberiaResurrection** [comment]
Kodermax,
Thanks for taking the time to report this bug.  I mucked this one up good and proper.

For the moment, you can work around by installing podata-laravel as dev-master, until I can cut a patch release of both packages with the dependencies appropriately fixed.

To answer my own curiosity, how are you using POData-Laravel?

**Comment by CyberiaResurrection** [comment]
I've fixed the mispointing in composer.json and am closing this bug report due to lack of response.
