### ISSUE TITLE
Odata 4.0

### ISSUE THREAD

**Issue by easysolvz** [Algo-Web/POData-Laravel#167]
Hi,

Thanks for the great work. Does POData-Laravel support Odata version 4.0?

Thanks

**Comment by c-harris** [comment]
Well, there I have some bad news. but also some good news. we currently don't support Version 4 because the[ core odata library we are developing](https://github.com/Algo-Web/POData) also lacks version 4 support. 

But the good news is that it is on the cards, and we are moving along with support for it. we currently have support to generate version 4 compatible metadata but can not as yet execute queries.

Sorry to disappoint but hopefully it is something that wont be to far away.

**Comment by easysolvz** [comment]
Thanks for your prompt response. In fact i currently have a service in .net with odata 4.0 and has to migrate it to php. What could be the best option?

**Comment by c-harris** [comment]
Well @easysolvz I'm sorry to say that i don't think there is a best option. @CyberiaResurrection and I needed a working service with write support and explored several different options in PHP before we started this project.

Depending on your time and skill I would be happy to work with you on implementing V4 support in [POData](https://github.com/Algo-Web/POData) Because i really don't think there is anything off the shelf that will do it.

But even if you don't want to help with V4 I would love to hear which way you go and would also be happy to offer any advice i can if you end up implementing it yourself.

Sorry i couldn't be more helpful.

**Comment by easysolvz** [comment]
Is there many changes to do to upgrade it to version 4.0?

**Comment by CyberiaResurrection** [comment]
We haven't really scoped out what's involved in adding 4.0 - @easysolvz , do you have a feature checklist that you would consider "implements OData v4.0"?

**Comment by easysolvz** [comment]
The expand feature in Odata 4.0 has changed as compared to version 3.0. Will this be implemented?
Also, is there any examaple how to call Odata in the existing  POData-Laravel?

**Comment by c-harris** [comment]
@easysolvz we would aim to expand to include all of odata V4, i will speak with @CyberiaResurrection shortly about a roadmap. and you are right, thre should be documentation on how to call the odata service. I believe you just need to point your browser at http://addressofserver/odata.svc

**Comment by easysolvz** [comment]
After doing a composer update on this project, I've tried to run  as http://localhost/podata-laravel/odata.svc and it does not work.

Any help please.

![image](https://user-images.githubusercontent.com/15217549/40408400-725e5d02-5e78-11e8-9264-5161a74c0e65.png)

**Comment by c-harris** [comment]
@easysolvz  did you hook up the services privders as per the ReadMe? also have you added the trait to the models you wish to expose?

**Comment by easysolvz** [comment]
The read me does not give any information about how to hookup the services. I've added the trait.

**Comment by c-harris** [comment]
**step 1**
Install Composer package
`composer require algo-web/podata-laravel
`
**Step 2** 
Add the Trait to the Models you wish to expose.

**Step 3**
Edit config/app.php and add providers :

```
AlgoWeb\PODataLaravel\Providers\MetadataProvider::class,
AlgoWeb\PODataLaravel\Providers\MetadataRouteProvider::class,
AlgoWeb\PODataLaravel\Providers\QueryProvider::class,
```

**Step 4**
Browse to the odata.svc route which will probably be at either /odata.svc or /public/odata.svc

**Comment by easysolvz** [comment]
Should i write MetadataProvider after that or it is ready to go and i can start querying Odata url?

**Comment by c-harris** [comment]
@easysolvz it is ready to go, odata.svc/$metadata to get the metadata and go from there.

**Comment by easysolvz** [comment]
I am having a new error as shown below.

![image](https://user-images.githubusercontent.com/15217549/40421502-34291674-5e9d-11e8-9371-125d2c99baba.png)

**Comment by c-harris** [comment]
@easysolvz I'm sorry you are having these issues. and i am happy to keep working through them with you (helps us narrow down issues). any chance you could let me know what version you have installed? (or show a copy of your compose.json?)

**Comment by c-harris** [comment]
@easysolvz I think the issue is in my instructions. and the README is out of date 
but i think if you 
Edit config/app.php and add an additional provider providers :
`AlgoWeb\PODataLaravel\Providers\MetadataControllerProvider::class,`

that should fix it

**Comment by easysolvz** [comment]
Thanks. I've included that line and it is downloading the definition file. Next step is just to include the trait in the model and it should work or should i configure anything else?

**Comment by c-harris** [comment]
Yep, include the trait in each model you want to expose, i recommend you configure a APP_METADATA_CACHING 
and
APP_METADATA_CACHE_DURATION 
which have huge performance bonus, but any information on that would need to come from @CyberiaResurrection

**Comment by easysolvz** [comment]
i've created a model class for Product as 



namespace App;

use PODataExample\models\EntityTrait;

class Product {

    // This trait contains method for fields mapping (between database table and this class)
   use EntityTrait;

    public $id;
    public $added_at;
    public $name;
    public $weight;
    public $code;
}

and it is not comming up with the URL http://localhost:8000/odata.svc/Product

**Comment by c-harris** [comment]
looks like you have added the wrong trait. you should be using 

`AlgoWeb\PODataLaravel\Models\MetadataTrait
`
you don't need the PODataExample package installed at all. it is a package that documents how to use POData without laravel.

**Comment by easysolvz** [comment]
I have tried the AlgoWeb\PODataLaravel\Models\MetadataTrait and am still getting the same error.

My svc file generated is as follows:

![image](https://user-images.githubusercontent.com/15217549/40440355-e26cee8c-5ece-11e8-90e8-0b2c1427057b.png)

**Comment by c-harris** [comment]
Can you show me the migration and model definition?

**Comment by CyberiaResurrection** [comment]
@easysolvz , I notice that your Product class doesn't extend the base Eloquent model class - what happens when you fix that?

**Comment by easysolvz** [comment]
Same error. Pls see my updated model class

![image](https://user-images.githubusercontent.com/15217549/40441387-f3848a06-5ed1-11e8-9bfb-d3da8e75f049.png)

**Comment by c-harris** [comment]
My bad, miss read, is the database migrated.

**Comment by easysolvz** [comment]
i've updated it as follows: same problem



namespace App;

use AlgoWeb\PODataLaravel\Models\ModeldataTrait;
use Illuminate\Database\Eloquent\Model;

class Product extends Model {

    // This trait contains method for fields mapping (between database table and this class)
   //use EntityTrait;
   use AlgoWeb\PODataLaravel\Models\ModeldataTrait;


    public $id;
    public $added_at;
    public $name;
    public $weight;
    public $code;
}

**Comment by c-harris** [comment]
Typo it should be metadata not modeldata

**Comment by easysolvz** [comment]
I have replace the modeldatatrait with metadatatrait. Still same problem

![image](https://user-images.githubusercontent.com/15217549/40442954-ecab28b2-5ed5-11e8-851b-1f8475cb582e.png)

**Comment by CyberiaResurrection** [comment]
@easysolvz , could you post your migration file that defines the database table that backs your Product model?

**Comment by c-harris** [comment]
@easysolvz ust to check, have you dumped the autoloader? 

`composer dump-autoload`

**Comment by easysolvz** [comment]
Hi
I am trying to read odata query from a url and convert it to eloquent query. Which part of you code can help me with that?

Thanks
