### ISSUE TITLE
Broken UTF-8 encoding

### ISSUE THREAD

**Issue by Kirich11** [Algo-Web/POData-Laravel#179]
Can't get correct display for strings
![image](https://user-images.githubusercontent.com/18256217/65442912-bacada00-de35-11e9-89fa-477c3b3610ab.png)

**Comment by c-harris** [comment]
That's a new one. Probably an issue in Podata itself but I'll take a look
in the next few days and let you know.

Thanks for reporting.

**Comment by Kirich11** [comment]
There was a triple utf8 encoding, one was in IronicSerialiser so I've removed it [https://github.com/Algo-Web/POData-Laravel/blob/master/src/Serialisers/IronicSerialiser.php#L877](here)

I have non-english text, so maybe use mutlibyte conversions?
Text is stored in a Mysql DB in utf8_general_ci encoding

**Comment by c-harris** [comment]
Well that saves me a lot of time tracking it down :) my only two languages
are English and bad English so I have not tested other languages but we
will take a look.

We are open to a pull request for mb encoding if you have the time. If not
we will try and get to it as soon as possible.

On a side note I notice you have an "isPaid" field that is a string.
Shouldn't that field be a bool?

**Comment by Kirich11** [comment]
> On a side note I notice you have an "isPaid" field that is a string. Shouldn't that field be a bool?

Indeed, it's an appended field and gets its value from a related model, maybe that's why it is a string

**Comment by Kirich11** [comment]
So you were right =)
The problem was in POData itself
Here's a link to a PR https://github.com/Algo-Web/POData/pull/215

Main fix is in OutgoingResponse, I had to force charset in the content-type header

Gonna close this. Thx for your quick response.
Feel free to do anything with PR. Glad to be helpful

**Comment by c-harris** [comment]
Thanks for that i will jump on the pull request shortly, Just FYI, if you put your attribute (appended field) in the $casts array on the model. PoData will read that. and case appropriately
