### ISSUE TITLE
$filter not working

### ISSUE THREAD

**Issue by drkmtrx** [Algo-Web/POData-Laravel#187]
When I call /Persons?$filter=name eq 'simon' i get the entire table.
In LaravelReadQuery.php applyFiltering() $rawLoad is always empty.
Is the $filter function supposed to work?

**Comment by c-harris** [comment]
Sorry bud, it had a rework sometime ago to remove reference to create function and I think it didn't go well. I believe a simple addition of

`$nullFilter = true`;

On line 110 of LaravelReadQuery (inside rhe if statment) should fix the problem but that is best guess from a man who hasn't slept in 36 hours.

I'm moving house atm but I'm still happy to try and help you debug it

**Comment by drkmtrx** [comment]
It is already set to true.
When I hardcode line 517 from
$resultSet = $sourceEntityInstance->skip($skip)->take($top)->with($rawLoad)->get();
to
$resultSet = $sourceEntityInstance->skip($skip)->take($top)->where('column', 'operator', 'value')->get();
it works.
Just need to get that dynamic.
So get your sleep and whenever possible have a look into this issue.
Thanks so far.

**Comment by CyberiaResurrection** [comment]
@bgoak , does #190 fix your filtering problem?  (Multi-level expansion will have to wait for another pull request).

**Comment by drkmtrx** [comment]
I build a workaround in https://github.com/bgoak/POData-Laravel/
I still need to test #190 but i will so do today.

**Comment by CyberiaResurrection** [comment]
@bgoak , thanks for replying.  Setting line 107 of LaravelReadQuery to 
`$nullFilter = !isset($filterInfo);`

insteadof
`$nullFilter = true;`

should be enough to let you verify if filtering is fixed.

**Comment by drkmtrx** [comment]
I tested #190 with a fresh install of POData-Laravel-NorthWind.
When i call /Persons?$filter=name eq 'simon' i get 
`<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code>500</code>
<message>Undefined variable: Person</message>
</error>`
So #190 does not fix this issue.

**Comment by CyberiaResurrection** [comment]
@bgoak , what happens when you try that url without the filter?

**Comment by drkmtrx** [comment]
Without the filter it works fine. Single expand also works fine.
But filter doesnt work at all.

**Comment by CyberiaResurrection** [comment]
@bgoak, really dumb question - in your testbed install of POData-Laravel-NorthWind, what's your dependency line for podata-laravel?

Also, are you able to dig out a stack trace for that 500?

**Comment by drkmtrx** [comment]
Heres my tree for podata-laravel:
`algo-web/podata-laravel dev-master Expose Odata services from laravel
├──algo-web/podata 0.3.*|dev-master
│  ├──algo-web/o-data-metadata 0.1.*|dev-master
│  │  ├──illuminate/support ^4.0|^5.1
│  │  ├──jms/serializer ^1.7
│  │  │  ├──doctrine/annotations ^1.0
│  │  │  │  ├──doctrine/lexer 1.*
│  │  │  │  │  └──php ^7.2
│  │  │  │  └──php ^7.1
│  │  │  ├──doctrine/instantiator ^1.0.3
│  │  │  │  └──php ^7.1
│  │  │  ├──jms/metadata ^1.3
│  │  │  │  └──php >=5.3.0
│  │  │  ├──jms/parser-lib 1.*
│  │  │  │  └──phpoption/phpoption >=0.9,<2.0-dev
│  │  │  │     └──php ^5.5.9 || ^7.0
│  │  │  ├──php ^5.5|^7.0
│  │  │  ├──phpcollection/phpcollection ~0.1
│  │  │  │  └──phpoption/phpoption 1.*
│  │  │  │     └──php ^5.5.9 || ^7.0
│  │  │  └──phpoption/phpoption ^1.1
│  │  │     └──php ^5.5.9 || ^7.0
│  │  └──php ~5.6|~7.0|~7.1
│  ├──illuminate/http >=5.1
│  ├──myclabs/php-enum 1.2.0
│  ├──nesbot/carbon ^1.0|^2.0
│  │  ├──kylekatarnls/update-helper ^1.1
│  │  │  ├──composer-plugin-api ^1.1.0 || ^2.0.0
│  │  │  └──php >=5.3.0
│  │  ├──php >=5.3.9
│  │  └──symfony/translation ~2.6 || ~3.0 || ~4.0
│  │     └──php >=5.3.9
│  └──php >=5.6.4
├──doctrine/dbal ^2.5
│  ├──doctrine/common ^2.7.1
│  │  ├──doctrine/annotations 1.*
│  │  │  ├──doctrine/lexer 1.*
│  │  │  │  └──php ^7.2
│  │  │  └──php ^7.1
│  │  ├──doctrine/cache 1.*
│  │  │  └──php ~7.1
│  │  ├──doctrine/collections 1.*
│  │  │  └──php ^7.1.3
│  │  ├──doctrine/inflector 1.*
│  │  │  └──php ^7.1
│  │  ├──doctrine/lexer 1.*
│  │  │  └──php ^7.2
│  │  └──php ~7.1
│  ├──ext-pdo *
│  └──php ^7.1
├──illuminate/http >=5.1.11
├──laravel/framework >=5.1.11
│  ├──classpreloader/classpreloader ~2.0|~3.0
│  │  ├──nikic/php-parser ^1.0|^2.0|^3.0
│  │  │  ├──ext-tokenizer *
│  │  │  └──php >=5.4
│  │  └──php >=5.5.9
│  ├──danielstjules/stringy ~1.8
│  │  ├──ext-mbstring *
│  │  └──php >=5.3.0
│  ├──doctrine/inflector ~1.0
│  │  └──php ^7.1
│  ├──ext-mbstring *
│  ├──ext-openssl *
│  ├──jeremeamia/superclosure ~2.0
│  │  ├──nikic/php-parser ^1.2|^2.0|^3.0|^4.0
│  │  │  ├──ext-tokenizer *
│  │  │  └──php >=5.4
│  │  ├──php >=5.4
│  │  └──symfony/polyfill-php56 ^1.0
│  ├──league/flysystem ~1.0
│  │  ├──ext-fileinfo *
│  │  └──php >=5.5.9
│  ├──monolog/monolog ~1.11
│  │  ├──php >=5.3.0
│  │  └──psr/log ~1.0
│  │     └──php >=5.3.0
│  ├──mtdowling/cron-expression ~1.0
│  │  └──php >=5.3.2
│  ├──nesbot/carbon ~1.19
│  │  ├──kylekatarnls/update-helper ^1.1
│  │  │  ├──composer-plugin-api ^1.1.0 || ^2.0.0
│  │  │  └──php >=5.3.0
│  │  ├──php >=5.3.9
│  │  └──symfony/translation ~2.6 || ~3.0 || ~4.0
│  │     └──php >=5.3.9
│  ├──paragonie/random_compat ~1.4|~2.0
│  │  └──php >=5.2.0
│  ├──php >=5.5.9
│  ├──psy/psysh 0.7.*
│  │  ├──dnoegel/php-xdg-base-dir 0.1
│  │  │  └──php >=5.3.2
│  │  ├──jakub-onderka/php-console-highlighter 0.3.*
│  │  │  ├──jakub-onderka/php-console-color ~0.1
│  │  │  │  └──php >=5.4.0
│  │  │  └──php >=5.3.0
│  │  ├──nikic/php-parser ^1.2.1|~2.0
│  │  │  ├──ext-tokenizer *
│  │  │  └──php >=5.4
│  │  ├──php >=5.3.9
│  │  ├──symfony/console ~2.3.10|^2.4.2|~3.0
│  │  │  ├──php >=5.3.9
│  │  │  └──symfony/debug ^2.7.2
│  │  │     ├──php >=5.3.9
│  │  │     └──psr/log ~1.0
│  │  │        └──php >=5.3.0
│  │  └──symfony/var-dumper ~2.7|~3.0
│  │     └──php >=5.3.9
│  ├──swiftmailer/swiftmailer ~5.1
│  │  └──php >=5.3.3
│  ├──symfony/console 2.7.*
│  │  ├──php >=5.3.9
│  │  └──symfony/debug ^2.7.2
│  │     ├──php >=5.3.9
│  │     └──psr/log ~1.0
│  │        └──php >=5.3.0
│  ├──symfony/css-selector 2.7.*|2.8.*
│  │  └──php >=5.3.9
│  ├──symfony/debug 2.7.*
│  │  ├──php >=5.3.9
│  │  └──psr/log ~1.0
│  │     └──php >=5.3.0
│  ├──symfony/dom-crawler 2.7.*
│  │  ├──php >=5.3.9
│  │  └──symfony/polyfill-ctype ~1.8
│  ├──symfony/finder 2.7.*
│  │  └──php >=5.3.9
│  ├──symfony/http-foundation 2.7.*
│  │  ├──php >=5.3.9
│  │  └──symfony/polyfill-mbstring ~1.1
│  ├──symfony/http-kernel 2.7.*
│  │  ├──php >=5.3.9
│  │  ├──psr/log ~1.0
│  │  │  └──php >=5.3.0
│  │  ├──symfony/debug ^2.6.2
│  │  │  ├──php >=5.3.9
│  │  │  └──psr/log ~1.0
│  │  │     └──php >=5.3.0
│  │  ├──symfony/event-dispatcher ^2.6.7
│  │  │  └──php >=5.3.9
│  │  ├──symfony/http-foundation ~2.7.36|^2.8.29
│  │  │  ├──php >=5.3.9
│  │  │  └──symfony/polyfill-mbstring ~1.1
│  │  └──symfony/polyfill-ctype ~1.8
│  ├──symfony/process 2.7.*
│  │  └──php >=5.3.9
│  ├──symfony/routing 2.7.*
│  │  └──php >=5.3.9
│  ├──symfony/translation 2.7.*
│  │  └──php >=5.3.9
│  ├──symfony/var-dumper 2.7.*
│  │  └──php >=5.3.9
│  └──vlucas/phpdotenv ~1.0
│     └──php >=5.3.2
├──php >=5.6.4
├──symfony/http-foundation ^2.7|^3.0|^4.0
│  ├──php >=5.3.9
│  └──symfony/polyfill-mbstring ~1.1
├──symfony/yaml ^2.7|^3.0|^4.0
│  └──php ^5.5.9|>=7.0.8
└──voku/anti-xss 2.1.*
   ├──php >=5.3.0
   └──voku/portable-utf8 ~3.1
      ├──php >=5.3.0
      └──symfony/polyfill ~1.0
         ├──ircmaxell/password-compat ~1.0
         ├──paragonie/random_compat ~1.0|~2.0|~9.99
         │  └──php >=5.2.0
         ├──php >=5.3.3
         └──symfony/intl ~2.3|~3.0|~4.0|~5.0
            ├──php ^7.2.5
            └──symfony/polyfill-intl-icu ~1.0`
The laravel.log does not report any errors, so i will try to find the source for that.

**Comment by CyberiaResurrection** [comment]
OK, thank you - I'm curious as to what you'll find.

**Comment by CyberiaResurrection** [comment]
@bgoak , I _think_ I've managed to repro with your instructions.

The filter info is now being processed, otherwise you wouldn't be hitting this issue - it looks like fixing the filter check has unmasked two other bugs, one fairly trivial, and the showstopper you've tripped over.  I've fixed those and got a with-filter call succeeding (as in returning 200) on my local copy of podata-laravel-northwind - it doesn't seem like that project has a Persons endpoint.

Can you please grab the latest commit on #190 and see if pain persists?

**Comment by drkmtrx** [comment]
Im glad I can confirm that this fixed the $filter issue.
You are right, I created my own test data which is not included in the northwind project.
However, when I call Persons/$count?$filter=name eq 'simon' I get a 
`<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code>500</code>
<message>
Call to undefined method Illuminate\Database\Query\Builder::with()
</message>
</error>`
Any ideas?

**Comment by CyberiaResurrection** [comment]
@bgoak , thanks for getting back to me.  With your report, I'll roll #190 up and close this issue.

Can you please add your latest bug report (on how $count and $filter interact badly) as a new issue?
It's roughly 4am local time here, so I won't be able to jump on it until at least 12 hours from now.

**Comment by drkmtrx** [comment]
No problem you already helped me a lot.
I opened a new Issue with #193.
Thanks so far.
