### ISSUE TITLE
Multi level expand not working

### ISSUE THREAD

**Issue by drkmtrx** [Algo-Web/POData-Laravel#188]
Single Persons?$expand=Address works but Persons?$expand=Address/City does not.
It seems like this is not implemented?

**Comment by drkmtrx** [comment]
In LaravelReadQuery.php $resourceSet contains all the content of the first and second expanded table.
So the command gets interpreted correctly, the tables called correctly but not added to the output.
My best guess right now is, that this issue correlates with #187 .
Am i wrong? And where should i have to look at if so?

**Comment by c-harris** [comment]
I think you are right and the two are related. I am very sorry for my lax replies. There are only two of us working on this project. I am currently moving house and @CyberiaResurrection is very short on time as he is covering a lot of my contract work while I'm shifting. 

I'll take a look now and see what I can work out. Are you using a stock install or have you made the changes you mentioned in #187?

**Comment by drkmtrx** [comment]
Thanks for the reply.
I build a workaround for me where i take $filterInfo->GetExpressionAsString() and process all the filter operators and stitch it together for $resultSet and $bulkSetCount. This was the fastest (and ugliest) fix i could come up with.
I can push my workaround in my fork tomorrow so you can better understand what i did.

**Comment by CyberiaResurrection** [comment]
@bgoak , in light of the fixes to filtering that have landed or are in flight, is this still a problem?

**Comment by drkmtrx** [comment]
After applying the fixes #190 and #195 this issue still persists.
Im also getting no results when I expand from Person to Address but Address to Person works fine.
Also /Person(personId='005e0745-ff78-426a-9c30-bd324b4ee329')/Address throws me back with a 204 No Content.
But /Address(addressId='6475cb2c-5907-44d6-bf2e-2402a7fcfcf0')/Person gets me a valid result.
Im using ramsey/uuid-doctrine for guid and modified Entities/EntityFieldPrimitiveType.php on line 53 to
`const GUID = 'uuid';`. Hope this doesnt breaks things.

In the inline tag on the result im only getting
`   <m:inline>
    <entry>
     <id></id>
     <title type="text"></title>
     <updated>2020-02-02T21:14:55+00:00</updated>
     <author>
      <name/>
     </author>
     <link rel="edit" title="" href=""/>
     <category term="" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
     <content type="application/xml">
      <m:properties/>
     </content>
    </entry>
   </m:inline>`

I still need to validate if thats a database error.

**Comment by c-harris** [comment]
Are you using the north wind database? (I'm wondering if it's  a bug in the relationship definition) 

I don't think the change to the enum would make any difference (it is just used for mapping database types to edm types to help cover the disconnect between type safe odata and non typesafe php.) Additionally I don't think the underlying uuid lib would make a difference.

If you are not using Northwind could you share the relation definitions in question? Because if they are correct the bug could relate to a specific type of relationship.

**Comment by drkmtrx** [comment]
Im not using the North Wind Database. I created my own test db with relevant relations for me.
I can provide you with my datebase tomorrow (in approx. 20 hours).

**Comment by drkmtrx** [comment]
This is what i use as Model:

```
class Person extends Model
{
    use \AlgoWeb\PODataLaravel\Models\MetadataTrait;
    protected $table = 'Person';
    public $timestamps = false;
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'personId';
    protected $fillable = [
        'name',
        'givenname',
        'addressid',
        'companyid'
    ];

    protected $guarded = [];

    public function Address()
    {
        return $this->belongsTo('App\Models\Address', 'addressid');
    }
}

class Address extends Model
{
    use \AlgoWeb\PODataLaravel\Models\MetadataTrait;
    protected $table = 'Address';
    public $timestamps = false;
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'addressId';
    protected $fillable = [
        'street',
        'cityid'
    ];

    protected $guarded = [];

    public function Person()
    {
        return $this->hasMany(Person::class, 'addressid');
    }

    public function City()
    {
        return $this->belongsTo('App\Models\City', 'cityid');
    }
}

class City extends Model
{
    use \AlgoWeb\PODataLaravel\Models\MetadataTrait;
    protected $table = 'City';
    public $timestamps = false;
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'cityId';
    protected $fillable = [
        'name',
        'postcode',
        'country'
    ];

    protected $guarded = [];

    public function Address()
    {
        return $this->hasMany(Address::class, 'cityid');
    }
}
```

**Comment by c-harris** [comment]
@bgoak that is very helpful. We should be able to the bottom of it. But in the interest of managing expectations the I will probably not be able to take a look before Thursday. If I find some free time we will.

**Comment by CyberiaResurrection** [comment]
@bgoak , I've started trying to chase this down in #199 .

I've checked the underlying relations in the models you supplied round-trip, checked that single expansions over your models work, and _think_ I've characterised the multiple-expansion failure you originally reported.  Can you please take a look at my efforts and see if I've gone off track?

**Comment by drkmtrx** [comment]
Looks good for me.
Maybe there should also be a test for more than two expands, like Persons?$expand=Address/City/Country.
Extending the model to:

```
class City extends Model
{
    use \AlgoWeb\PODataLaravel\Models\MetadataTrait;
    protected $table = 'City';
    public $timestamps = false;
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'cityId';
    protected $fillable = [
        'name',
        'postcode',
        'countryid'
    ];

    protected $guarded = [];

    public function Address()
    {
        return $this->hasMany(Address::class, 'cityid');
    }

    public function Country()
    {
        return $this->belongsTo('App\Models\Country', 'countryid');
    
}

class Country extends Model
{
    use \AlgoWeb\PODataLaravel\Models\MetadataTrait;
    protected $table = 'Country';
    public $timestamps = false;
    public $incrementing = false;
    protected $keyType = 'string';
    protected $primaryKey = 'countryId';
    protected $fillable = [
        'name',
        'countryCode'
    ];

    protected $guarded = [];

    public function City()
    {
        return $this->hasMany(City::class, 'countryid');
    }
}
```

Just to be on the safe side. I guess when triple expand works so should every expand after that.
Thanks so far for tracking this down.

**Comment by CyberiaResurrection** [comment]
@bgoak , can you try the head of #199 and see if that sorts you out?

**Comment by drkmtrx** [comment]
I can confirm this seems to have fixed the issue, triple expansion works as well.
I will do a fresh installation and do some more tests with it but this seems very promising.

**Comment by CyberiaResurrection** [comment]
@bgoak , thanks for the quick reply and glad to hear that at first pass, you're out of strife.

I should have this merged up tonight AEST, and please keep hammering on POData-Laravel to help us wring out lurking problems.
