### ISSUE TITLE
$count with applied $filter not working

### ISSUE THREAD

**Issue by drkmtrx** [Algo-Web/POData-Laravel#193]
When I call Persons/$count?$filter=name eq 'simon' I get a
`<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"> <code>500</code> <message> Call to undefined method Illuminate\Database\Query\Builder::with() </message> </error>`

**Comment by CyberiaResurrection** [comment]
@bgoak , thanks for breaking this out as a separate issue - makes it easier to keep track of.

**Comment by c-harris** [comment]
@bgoak just to let you know we are working on improving the unit tests to resolve a lot of these issues

**Comment by CyberiaResurrection** [comment]
@bgoak , can you grab #195 and see if this fixes your problem?

**Comment by drkmtrx** [comment]
I can confirm that #195 fixed this issue.
Thank you.

**Comment by CyberiaResurrection** [comment]
Closing since @bgoak has confirmed fix.
