### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by renanwilliam** [Algo-Web/POData-Laravel#51]
This package works on Laravel 5.4? I have installed but facing a lot of erros, can't make it work in anyway.

**Comment by c-harris** [comment]
G'day @renanwilliam ,

Sorry to hear you are facing a lot of errors, My current project is on laravel 5.1 so i am unsure about 5.4. I will however ask @CyberiaResurrection to look into it as he is our resident Laravel expert.

what would help is if you let us know what sort of errors you are facing and we might be able to help you fix them

**Comment by CyberiaResurrection** [comment]
Renan, as our fearless leader indicated, I'm the one who's been trying to make POData-Laravel polyglot across L5.1 thru 5.5.  I was more expecting to hear I'd mucked something up in L5.2 or 5.3.

Could you provide some more detail about what errors you've been experiencing?
One thing I've found is that the bidirectional-relationship gubbins does form an isOK over your set of inter-model relationship - as I've found out (hard way), although stock L5 will happily connect a belongsTo to another belongsTo, POData-Laravel will barf on that.

**Comment by CyberiaResurrection** [comment]
Renan,
I think we've fixed metadata caching - we've definitely done so in our testbeds.  Could you run composer update and see if pain persists?

**Comment by CyberiaResurrection** [comment]
Closing due to lack of reponse

**Comment by renanwilliam** [comment]
Sorry about the late. I was working in another feature and no times to other things. I have update my project now.

In `AlgoWeb\PODataLaravel\Controllers\ODataController`  it have:
```php
Storage::put($xTest.'request', $cerealRequest);
Storage::put($xTest.'metadata', $cerealMeta);
Storage::put($xTest.'response', $cerealResponse);
```

It always throws a error :
`file_put_contents(C:\xampp\htdocs\api-egsa\storage\app\GET;odata.svc-$metadata;19:20:51;request): failed to open stream: No such file or directory`

What is about this files? It's for cache?

**Comment by CyberiaResurrection** [comment]
Hey @renanwilliam,

That block in ODataController is there to dump out request-response-metadata pairs for regression testing - and thus can be safely left disabled (APP_DUMP_REQUESTS in your .env file either missing or not set anything but true).

**Comment by renanwilliam** [comment]
Hi @CyberiaResurrection, thanks for your quick responses.

I think that the parameter `APP_DUMP_REQUESTS` is overwritten by $dump parameter send in ODataController when we requesting data with some parameter here:
```php
public function index(Request $request, $dump = false)
{
    $dump = $dump || $this->getIsDumping();
    ...
}
```

The route is: 
```php
Route::any(
            'odata.svc/{section}',
            [ 'uses' => 'AlgoWeb\PODataLaravel\Controllers\ODataController@index', 'middleware' => 'auth:api']
        )
            ->where(['section' => '.*']);
```

So if I call `/odata.svc/$metadata`, the $dump parameter will set as $metadata and will overwrite the APP_DUMP_REQUESTS parameter.

**Comment by CyberiaResurrection** [comment]
@renanwilliam , thanks for chasing that down - I think I outsmarted myself there.

If $dump is being set to true, as you've pointed out, then APP_DUMP_REQUESTS never comes into it - that expression's left hand side is true, so it short-circuits to true.

**Comment by CyberiaResurrection** [comment]
Can you pull changes (via composer,  git, however you do it) and see if the problem persists?

**Comment by renanwilliam** [comment]
Hi @CyberiaResurrection, now it's ok!! Working out of box in Laravel 5.4 :)
