### ISSUE TITLE
What is implemented?

### ISSUE THREAD

**Issue by renanwilliam** [Algo-Web/POData-Laravel#65]
Could you please detail what are OData features and versions implemented in package?

**Comment by c-harris** [comment]
Hi @renanwilliam at the moment we have extensive read only support for V3, at the moment data requests are sorted, exposure of models is automatic with a trait. and we have setup a system to simulate singletons through odata functions. 

we are dedicating most of our time at the moment to extending feature support and stabilizing write support in the parent POData project. But if there are any specific features that you are looking for @CyberiaResurrection is the ideal contact for laravel side, and i would be the best person to contact for any oData related bits.

**Comment by renanwilliam** [comment]
Hi,

I think that is a good ideia keep some control like this in README.md file:
## Support Feature

* [ ] Full CRUD Support
* [ ] $count
* [ ] $filter
  * [ ] Comparison Operators
  	* [ ] eq
  	* [ ] ne
  	* [ ] lt
  	* [ ] le
  	* [ ] gt
  	* [ ] ge
  * [ ] Logical Operators
  	* [ ] and
  	* [ ] or
  	* [ ] not
  * [ ] Comparison Operators
    * [ ] has
  * [ ] String Functions
  	* [ ] indexof
  	* [ ] contains
  	* [ ] endswith
  	* [ ] startswith
  	* [ ] length
  	* [ ] substring
  	* [ ] tolower
  	* [ ] toupper
  	* [ ] trim
  	* [ ] concat
  * [ ] Arithmetic Operators
  	* [ ] add
  	* [ ] sub
  	* [ ] mul
  	* [ ] div
  	* [ ] mod
  * [ ] Date Functions
  	* [ ] year
  	* [ ] month
  	* [ ] day
  	* [ ] hour
  	* [ ] minute
  	* [ ] second
  	* [ ] fractionalseconds
  	* [ ] date
  	* [ ] time
  	* [ ] totaloffsetminutes
  	* [ ] now
  	* [ ] mindatetime
  	* [ ] maxdatetime
  * [ ] Math Functions
  	* [ ] round
  	* [ ] floor
  	* [ ] ceiling
* [ ] $select
* [ ] $top
* [ ] $skip
* [x] $orderby
* [ ] $expand
* [ ] $metadata generation (Nonstandard)

It will be important to mensure how mature is the repository and will attract more contributors.

**Comment by c-harris** [comment]
@CyberiaResurrection I think he is onto something here, I think we should implement that on this and the parent project.

**Comment by CyberiaResurrection** [comment]
Yes, that is a damn good idea - given ancestral claims of "full OData v3 support, guaranteed" have shown to be a little hollow.  @renanwilliam is on fire today.

**Comment by c-harris** [comment]
@renanwilliam we are adding your list at the moment, I just wanted to ask what you mean by  $metadata generation (Nonstandard) ?

**Comment by renanwilliam** [comment]
@c-harris non-standard $metadata is not relevant I think, in other repositories it's show a document using another format that isn't the described in OData specification and is used in a start level of development just for tests. Your package already the standard $metadata format and that is the most important feature.
